In [1]:
import pandas as pd
import quandl
import math

In [2]:
df = pd.read_csv("/home/senko/Desktop/WIKI_PRICES.csv")

In [3]:
df.head()

ticker        date   open   high    low  close      volume  ex-dividend  \
0      A  1999-11-18  45.50  50.00  40.00  44.00  44739900.0          0.0   
1      A  1999-11-19  42.94  43.00  39.81  40.38  10897100.0          0.0   
2      A  1999-11-22  41.31  44.00  40.06  44.00   4705200.0          0.0   
3      A  1999-11-23  42.50  43.63  40.25  40.25   4274400.0          0.0   
4      A  1999-11-24  40.13  41.94  40.00  41.06   3464400.0          0.0   

   split_ratio   adj_open   adj_high    adj_low  adj_close  adj_volume  
0          1.0  31.041951  34.112034  27.289627  30.018590  44739900.0  
1          1.0  29.295415  29.336350  27.160002  27.548879  10897100.0  
2          1.0  28.183363  30.018590  27.330562  30.018590   4705200.0  
3          1.0  28.995229  29.766161  27.460188  27.460188   4274400.0  
4          1.0  27.378319  28.613174  27.289627  28.012803   3464400.0

In [4]:
googl = df.loc[df['ticker'] == 'GOOGL']

In [5]:
googl

ticker        date     open     high      low     close      volume  \
6103168  GOOGL  2004-08-19   100.01   104.06    95.96   100.335  44659000.0   
6103169  GOOGL  2004-08-20   101.01   109.08   100.50   108.310  22834300.0   
6103170  GOOGL  2004-08-23   110.76   113.48   109.05   109.400  18256100.0   
6103171  GOOGL  2004-08-24   111.24   111.60   103.57   104.870  15247300.0   
6103172  GOOGL  2004-08-25   104.76   108.00   103.88   106.000   9188600.0   
...        ...         ...      ...      ...      ...       ...         ...   
6106587  GOOGL  2018-03-21  1092.57  1108.70  1087.21  1094.000   1990515.0   
6106588  GOOGL  2018-03-22  1080.01  1083.92  1049.64  1053.150   3418154.0   
6106589  GOOGL  2018-03-23  1051.37  1066.78  1024.87  1026.550   2413517.0   
6106590  GOOGL  2018-03-26  1050.60  1059.27  1010.58  1054.090   3272409.0   
6106591  GOOGL  2018-03-27  1063.90  1064.54   997.62  1006.940   2940957.0   

         ex-dividend  split_ratio     adj_open     adj_high      adj_low  \
6103168          0.0          1.0    50.159839    52.191109    48.128568   
6103169          0.0          1.0    50.661387    54.708881    50.405597   
6103170          0.0          1.0    55.551482    56.915693    54.693835   
6103171          0.0          1.0    55.792225    55.972783    51.945350   
6103172          0.0          1.0    52.542193    54.167209    52.100830   
...              ...          ...          ...          ...          ...   
6106587          0.0          1.0  1092.570000  1108.700000  1087.210000   
6106588          0.0          1.0  1080.010000  1083.920000  1049.640000   
6106589          0.0          1.0  1051.370000  1066.780000  1024.870000   
6106590          0.0          1.0  1050.600000  1059.270000  1010.580000   
6106591          0.0          1.0  1063.900000  1064.540000   997.620000   

           adj_close  adj_volume  
6103168    50.322842  44659000.0  
6103169    54.322689  22834300.0  
6103170    54.869377  18256100.0  
6103171    52.597363  15247300.0  
6103172    53.164113   9188600.0  
...              ...         ...  
6106587  1094.000000   1990515.0  
6106588  1053.150000   3418154.0  
6106589  1026.550000   2413517.0  
6106590  1054.090000   3272409.0  
6106591  1006.940000   2940957.0  

[3424 rows x 14 columns]

In [6]:
# take some spesific columns
googl = googl[['date', 'adj_open', 'adj_high', 'adj_low', 'adj_close', 'adj_volume',]]

In [7]:
googl

date     adj_open     adj_high      adj_low    adj_close  \
6103168  2004-08-19    50.159839    52.191109    48.128568    50.322842   
6103169  2004-08-20    50.661387    54.708881    50.405597    54.322689   
6103170  2004-08-23    55.551482    56.915693    54.693835    54.869377   
6103171  2004-08-24    55.792225    55.972783    51.945350    52.597363   
6103172  2004-08-25    52.542193    54.167209    52.100830    53.164113   
...             ...          ...          ...          ...          ...   
6106587  2018-03-21  1092.570000  1108.700000  1087.210000  1094.000000   
6106588  2018-03-22  1080.010000  1083.920000  1049.640000  1053.150000   
6106589  2018-03-23  1051.370000  1066.780000  1024.870000  1026.550000   
6106590  2018-03-26  1050.600000  1059.270000  1010.580000  1054.090000   
6106591  2018-03-27  1063.900000  1064.540000   997.620000  1006.940000   

         adj_volume  
6103168  44659000.0  
6103169  22834300.0  
6103170  18256100.0  
6103171  15247300.0  
6103172   9188600.0  
...             ...  
6106587   1990515.0  
6106588   3418154.0  
6106589   2413517.0  
6106590   3272409.0  
6106591   2940957.0  

[3424 rows x 6 columns]

In [8]:
# googl['HL_PCT'] = (googl['adj_high'] - googl['adj_close']) / googl['adj_close'] * 100.0
# above statement will give warning SettingWithCopyWarning
# best way to create a new column in existing dataframe is using assign
googl = googl.assign(HL_PCT = (googl['adj_high'] - googl['adj_close']) / googl['adj_close'] * 100.0)
googl = googl.assign(PCT_change = (googl['adj_close'] - googl['adj_open']) / googl['adj_open'] * 100.0)

In [9]:
googl

date     adj_open     adj_high      adj_low    adj_close  \
6103168  2004-08-19    50.159839    52.191109    48.128568    50.322842   
6103169  2004-08-20    50.661387    54.708881    50.405597    54.322689   
6103170  2004-08-23    55.551482    56.915693    54.693835    54.869377   
6103171  2004-08-24    55.792225    55.972783    51.945350    52.597363   
6103172  2004-08-25    52.542193    54.167209    52.100830    53.164113   
...             ...          ...          ...          ...          ...   
6106587  2018-03-21  1092.570000  1108.700000  1087.210000  1094.000000   
6106588  2018-03-22  1080.010000  1083.920000  1049.640000  1053.150000   
6106589  2018-03-23  1051.370000  1066.780000  1024.870000  1026.550000   
6106590  2018-03-26  1050.600000  1059.270000  1010.580000  1054.090000   
6106591  2018-03-27  1063.900000  1064.540000   997.620000  1006.940000   

         adj_volume    HL_PCT  PCT_change  
6103168  44659000.0  3.712563    0.324968  
6103169  22834300.0  0.710922    7.227007  
6103170  18256100.0  3.729433   -1.227880  
6103171  15247300.0  6.417469   -5.726357  
6103172   9188600.0  1.886792    1.183658  
...             ...       ...         ...  
6106587   1990515.0  1.343693    0.130884  
6106588   3418154.0  2.921711   -2.487014  
6106589   2413517.0  3.918952   -2.360729  
6106590   3272409.0  0.491419    0.332191  
6106591   2940957.0  5.720301   -5.353887  

[3424 rows x 8 columns]

In [10]:
googl = googl[['date', 'adj_close', 'HL_PCT', 'PCT_change', 'adj_volume']]

In [11]:
googl

date    adj_close    HL_PCT  PCT_change  adj_volume
6103168  2004-08-19    50.322842  3.712563    0.324968  44659000.0
6103169  2004-08-20    54.322689  0.710922    7.227007  22834300.0
6103170  2004-08-23    54.869377  3.729433   -1.227880  18256100.0
6103171  2004-08-24    52.597363  6.417469   -5.726357  15247300.0
6103172  2004-08-25    53.164113  1.886792    1.183658   9188600.0
...             ...          ...       ...         ...         ...
6106587  2018-03-21  1094.000000  1.343693    0.130884   1990515.0
6106588  2018-03-22  1053.150000  2.921711   -2.487014   3418154.0
6106589  2018-03-23  1026.550000  3.918952   -2.360729   2413517.0
6106590  2018-03-26  1054.090000  0.491419    0.332191   3272409.0
6106591  2018-03-27  1006.940000  5.720301   -5.353887   2940957.0

[3424 rows x 5 columns]

In [12]:
forecast_col = 'adj_close'
googl.fillna(-99999, inplace=True)
forecast_out = int(math.ceil(0.01*len(googl)))
googl['label'] = googl[forecast_col].shift(-forecast_out)
print(forecast_out)

35


/home/senko/miniconda3/envs/sentdex/lib/python3.6/site-packages/pandas/core/frame.py:4259: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  **kwargs
/home/senko/miniconda3/envs/sentdex/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [13]:
len(googl)

3424

In [14]:
googl

date    adj_close    HL_PCT  PCT_change  adj_volume      label
6103168  2004-08-19    50.322842  3.712563    0.324968  44659000.0  69.078238
6103169  2004-08-20    54.322689  0.710922    7.227007  22834300.0  67.839414
6103170  2004-08-23    54.869377  3.729433   -1.227880  18256100.0  68.912727
6103171  2004-08-24    52.597363  6.417469   -5.726357  15247300.0  70.668146
6103172  2004-08-25    53.164113  1.886792    1.183658   9188600.0  71.219849
...             ...          ...       ...         ...         ...        ...
6106587  2018-03-21  1094.000000  1.343693    0.130884   1990515.0        NaN
6106588  2018-03-22  1053.150000  2.921711   -2.487014   3418154.0        NaN
6106589  2018-03-23  1026.550000  3.918952   -2.360729   2413517.0        NaN
6106590  2018-03-26  1054.090000  0.491419    0.332191   3272409.0        NaN
6106591  2018-03-27  1006.940000  5.720301   -5.353887   2940957.0        NaN

[3424 rows x 6 columns]

In [15]:
import numpy as np

In [16]:
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [17]:
googl = googl.drop(['date'], 1)
X = np.array(googl.drop(['label'], 1))
y = np.array(googl['label'])

In [18]:
X

array([[ 5.03228418e+01,  3.71256291e+00,  3.24967503e-01,
         4.46590000e+07],
       [ 5.43226889e+01,  7.10922353e-01,  7.22700723e+00,
         2.28343000e+07],
       [ 5.48693765e+01,  3.72943327e+00, -1.22788010e+00,
         1.82561000e+07],
       ...,
       [ 1.02655000e+03,  3.91895183e+00, -2.36072933e+00,
         2.41351700e+06],
       [ 1.05409000e+03,  4.91419139e-01,  3.32191129e-01,
         3.27240900e+06],
       [ 1.00694000e+03,  5.72030111e+00, -5.35388664e+00,
         2.94095700e+06]])

In [19]:
y

array([69.0782379 , 67.83941377, 68.91272699, ...,         nan,
               nan,         nan])

In [20]:
X = preprocessing.scale(X)

In [21]:
X

array([[-1.39187095,  2.33516806,  0.23254018,  4.46712802],
       [-1.37635178, -0.31135438,  4.81828847,  1.8207495 ],
       [-1.37423066,  2.35004252, -0.79917922,  1.26561472],
       ...,
       [ 2.39583323,  2.51713951, -1.55184968, -0.65539548],
       [ 2.50268682, -0.50488861,  0.23733959, -0.55124957],
       [ 2.31974758,  4.10537475, -3.54051775, -0.59144015]])

In [22]:
#X = X[:-forecast_out+1]

In [23]:
X

array([[-1.39187095,  2.33516806,  0.23254018,  4.46712802],
       [-1.37635178, -0.31135438,  4.81828847,  1.8207495 ],
       [-1.37423066,  2.35004252, -0.79917922,  1.26561472],
       ...,
       [ 2.39583323,  2.51713951, -1.55184968, -0.65539548],
       [ 2.50268682, -0.50488861,  0.23733959, -0.55124957],
       [ 2.31974758,  4.10537475, -3.54051775, -0.59144015]])

In [24]:
googl.dropna(inplace=True)

In [25]:
y = np.array(googl['label'])

In [26]:
print(len(X), len(y))

3424 3389


In [ ]:
X_train, X_test, y_train, y_test =  