In [1]:
import numpy as np

In [11]:
vector_row = np.array([1,2,3,4])

In [12]:
vector_row

array([1, 2, 3, 4])

In [13]:
matrix = np.mat([
    np.random.randint(low=1, high=100, size=4),
    np.random.randint(low=1, high=100, size=4),
    np.random.randint(low=1, high=100, size=4)
])

In [14]:
matrix

matrix([[51, 87, 13, 70],
        [87,  7, 60, 57],
        [25, 49, 94, 68]])

In [15]:
new_vector = matrix.dot(vector_row)

In [16]:
new_vector

matrix([[544, 509, 677]])

In [17]:
matrix2 = np.mat([
    np.random.randint(low=1, high=100, size=4),
    np.random.randint(low=1, high=100, size=4),
    np.random.randint(low=1, high=100, size=4),
    np.random.randint(low=1, high=100, size=4),
    np.random.randint(low=1, high=100, size=4),
    np.random.randint(low=1, high=100, size=4)
])

In [18]:
matrix2

matrix([[ 5, 72, 45, 35],
        [40, 29,  1, 37],
        [31,  7, 30, 21],
        [76, 84, 22, 13],
        [25, 31, 77, 12],
        [48, 93, 60, 84]])

In [19]:
matrix2.transpose()

matrix([[ 5, 40, 31, 76, 25, 48],
        [72, 29,  7, 84, 31, 93],
        [45,  1, 30, 22, 77, 60],
        [35, 37, 21, 13, 12, 84]])

In [20]:
matrix3 = matrix.dot(matrix2.transpose())

In [21]:
matrix3

matrix([[ 9554,  7166,  4050, 12380,  5813, 17199],
        [ 5634,  5852,  5743,  9261,  7696, 13215],
        [10263,  5031,  5366,  8968, 10198, 17109]])